pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Build'  // steps or sh commands go here...
            }
        }
        stage('Test') {
            steps {
                echo 'Test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy'
            }
        }
    }
}
