wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.12
    start_time: 1645654145
    t:
      4: 3.8.12
      5: 0.12.10
      8:
      - 1
      - 2
      - 5
